In [2]:
import numpy as np

In [ ]:
#  Creating Arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(0, 10, 2)        # [0 2 4 6 8]
arr3 = np.linspace(0, 1, 5)       # 5 values between 0 and 1
arr4 = np.zeros((2, 3))           # 2x3 array of zeros
arr5 = np.ones((3, 3))            # 3x3 array of ones
arr6 = np.eye(3)                  # Identity matrix
arr7 = np.random.rand(2, 2)       # Random floats [0,1)
arr8 = np.random.randint(1, 10, 5) # 5 random integers 1–9

print("arr1:", arr1)
print("arr2:", arr2)
print("arr3:", arr3)
print("arr4:\n", arr4)
print("arr7:\n", arr7)

arr1: [1 2 3 4 5]
arr2: [0 2 4 6 8]
arr3: [0.   0.25 0.5  0.75 1.  ]
arr4:
 [[0. 0. 0.]
 [0. 0. 0.]]
arr7:
 [[0.58735765 0.78540185]
 [0.08178568 0.55159543]]


In [ ]:
#  Array Operations
arr = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Std Dev:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Cumulative Sum:", np.cumsum(arr))
print("Cumulative Product:", np.cumprod(arr))

Sum: 15
Mean: 3.0
Std Dev: 1.4142135623730951
Min: 1
Max: 5
Cumulative Sum: [ 1  3  6 10 15]
Cumulative Product: [  1   2   6  24 120]


In [ ]:
#  Reshaping & Indexing
matrix = np.arange(1, 10).reshape(3, 3)
print("Matrix:\n", matrix)

print("First row:", matrix[0])
print("First column:", matrix[:, 0])
print("Element at (1,2):", matrix[1, 2])
print("Slicing (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
First column: [1 4 7]
Element at (1,2): 6
Slicing (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]


In [4]:
#  Broadcasting
a = np.array([1, 2, 3])
b = np.array([10])
print("a + b:", a + b)  # Adds 10 to each element

a + b: [11 12 13]
